### ISSUE TITLE
build: zcutils/build.sh fails on non-debian based 64-bit Linux distros

### ISSUE THREAD

**Issue by prusnak** [zcash/zcash#2294]
(e.g. openSUSE and/or CentOS)

`./zcutils/build.sh` fails because `configure` cannot find Boost libraries.

This happens, because `make depends` puts some of the libraries in `depends/x86_64-unknown-linux-gnu/lib` and some in `depends/x86_64-unknown-linux-gnu/lib64`

Traditionaly, these distros use `/usr/lib` as libdir for 32-bit and `/usr/lib64` for 64-bit.

I suspect that some of the libraries (such as boost and others, see comment below) have hardcoded `lib` element of the path and not use the system one (`lib64`) like the others.

**Comment by prusnak** [comment]
For reference:

```
$ ls -F depends/x86_64-unknown-linux-gnu/lib
engines-1.1/
libboost_chrono-mt.a
libboost_filesystem-mt.a
libboost_prg_exec_monitor-mt.a
libboost_program_options-mt.a
libboost_system-mt.a
libboost_test_exec_monitor-mt.a
libboost_thread-mt.a
libboost_timer-mt.a
libboost_unit_test_framework-mt.a
libcrypto.a
libgmock.a*
libgtest.a*
libminiupnpc.a*
librustzcash.a
libsnark.a
libssl.a
pkgconfig/
```

```
$ ls -F depends/x86_64-unknown-linux-gnu/lib64
cmake/
libdb-6.2.a
libdb.a
libdb_cxx-6.2.a
libdb_cxx.a
libevent.a
libevent_core.a
libevent_core.la*
libevent_extra.a
libevent_extra.la*
libevent.la*
libevent_pthreads.a
libevent_pthreads.la*
libgmp.a
libgmp.la*
libgmpxx.a
libgmpxx.la*
libqpid-proton.a
libqpid-proton-core.a
libqpid-proton-cpp.a
libsodium.a
libsodium.la*
libzmq.a
libzmq.la*
pkgconfig/
```

**Comment by radix42** [comment]
The build script, `zcutil/build.sh` builds them all from source in the `depends/` folder, it does NOT expect to find nor does it use boost (or other dependencies) installed by the system.

**Comment by prusnak** [comment]
@radix42 Read my report again, or ideally try this on distro I mentioned. The breakage is in the `depends/` folder.

**Comment by prusnak** [comment]
Further investigations shows that libraries affected by the breakage are most probably the ones that do not use pkg-config. (For example, libssl is fine even when places in `depends/x86_64-unknown-linux-gnu/lib`, but its pkg-config file states lib instead of lib64 correctly).

**Comment by ebfull** [comment]
This just started happening to me as well and I'm not sure why yet. Did we recently update boost or change something in configure?

**Comment by radix42** [comment]
I am going to attempt to replicate on the default version of OpenSuse that Amazon gives you

**Comment by radix42** [comment]
I also have RHEL and AmazonLinux systems to test on, but I have not built on them since before 1.0.8-1 (not sure how far back I built on them)

**Comment by radix42** [comment]
Hm is your issue with building specifically on Suse or on Centos? I can build fine on RHEL and Amazon Linux, but am not up to speed on Suse recently enough to get my freaking toolchain installed right.

What distro (and version) are you on and what command line are you using to install all of the build tools (the equivalent to what is given for Debian/Ubuntu and Fedora at https://github.com/zcash/zcash/wiki/1.0-User-Guide#install-dependencies ?)

**Comment by prusnak** [comment]
Are you sure you are using 64-bit versions?
The same issue is happening on both openSUSE 13.3 and CentOS 7.2.

**Comment by radix42** [comment]
it won't build on anything BUT 64 bit, so yes :-)

I'm launching a CentOS 7.2 virtual machine as I type (I am comfortable with RedHat and Debian derived distros, but lost in Suse-land)

**Comment by radix42** [comment]
ok yes that fails in exactly the way you're describing. I'm gonna have to leave this one for ZcashCo staff to figure out, I'm currently tied up with too many things to spend more time on it.

**Comment by ebfull** [comment]
It's something to do with the Proton stuff.

`./zcutil/build.sh --disable-proton -j4` fixes it.

**Comment by bitcartel** [comment]
@ebfull Can you show me the log output?  The proton library tries to build many language bindings and this was disabled but one slipped through (javascript - which @str4d saw and that has been fixed in a PR) but maybe there is another language too.

**Comment by ebfull** [comment]
I was receiving an error during configure: `Could not find a version of the boost_system library!` I'll get a better log for you later.

It only stopped when I passed --disable-proton as it was the only thing that I could think of that changed in the build system.

**Comment by daira** [comment]
@ebfull Does it work if you merge https://github.com/zcash/zcash/pull/2280 ?

**Comment by nathan-at-least** [comment]
We've decided not to focus on this for the 1.0.11 release _but_ we're doing some important ground-work first:

- #2509 so that we can start adding continuous integration for more platforms/distros.
- Some other distro workers.

So this release will establish a new framework and test it against other distros. If that works well we can add OpenSUSE and CentOS workers.

**Comment by Haaroon** [comment]
Yeah, I'm assuming this isnt fixed as I still get an error on CentOS when trying to build
> invalid configuration machine not recognised

**Comment by jasondavies** [comment]
I just completed a build on CentOS 7 (`CentOS-7-x86_64-Minimal-1708.iso`) using a VirtualBox VM (64-bit) with no errors.  The commands I used are as follows:

```sh
yum install git
yum install centos-release-scl-rh
yum install devtoolset-3-gcc devtoolset-3-gcc-c++
yum install bzip2 patch automake libtool glibc-static

scl enable devtoolset-3 bash
git clone https://github.com/zcash/zcash.git

cd zcash
./zcutils/build.sh
```

**Comment by jasondavies** [comment]
I ran into some of the issues described above when attempting a build on openSUSE 42.3 (`openSUSE-Leap-42.3-NET-x86_64.iso`).

The first issue was the error ``Invalid configuration `linux-6qt8': machine `linux' not recognized``.  After some digging, I found that the environment variable `HOST` was set to `linux-6qt8` causing the above issue (this variable doesn't seem to be set by default on other distributions).  A workaround is simply to run `HOST= ./zcutils/build.sh`.

Then, I ran into the boost error mentioned above.  The following patch should fix this issue:

```diff
diff --git a/build-aux/m4/ax_boost_base.m4 b/build-aux/m4/ax_boost_base.m4
index 45d94893..043fea01 100644
--- a/build-aux/m4/ax_boost_base.m4
+++ b/build-aux/m4/ax_boost_base.m4
@@ -124,7 +124,7 @@ if test "x$want_boost" = "xyes"; then
     if test "$ac_boost_path" != ""; then
         BOOST_CPPFLAGS="-I$ac_boost_path/include"
         for ac_boost_path_tmp in $libsubdirs; do
-                if test -d "$ac_boost_path"/"$ac_boost_path_tmp" ; then
+                if ls "$ac_boost_path/$ac_boost_path_tmp/libboost_"* >/dev/null 2>&1 ; then
                         BOOST_LDFLAGS="-L$ac_boost_path/$ac_boost_path_tmp"
                         break
                 fi
```

(The problem is that `$libsubdirs` is both `lib` and `lib64`, and it simply picks the first one if it exists without checking whether it contains the boost library.  That strange-looking line is similar to a check elsewhere in the same file.)

The last issue (hopefully) is that it can't seem to find libevent:

```sh
configure: error: libevent not found.
$ ls depends/x86_64-unknown-linux-gnu/lib*/pkgconfig
depends/x86_64-unknown-linux-gnu/lib/pkgconfig:
libcrypto.pc
libssl.pc
openssl.pc

depends/x86_64-unknown-linux-gnu/lib64/pkgconfig:
libevent.pc
libevent_core.pc
libevent_extra.pc
libevent_pthreads.pc
libsodium.pc
libzmq.pc
```

It seems there are two pkgconfig directories, one in each of `lib` and `lib64`.

**Comment by mdr0id** [comment]
(Closing)

Justification 
The scope of this ticket is fairly broad. I am able to build on a few 64bit distros and also cross verified with other developers internally. The relevant build steps have been migrated into ReadtheDocs to parallel existing supported CI platforms.

If this is reopened, we should consider making tickets more granular (e.g. 64-bit distro and its associated errors/ resolution procedure). This is intended to help the CI integration and legacy documentation.
