### ISSUE TITLE
libsodium fails to build when cross-compiling to Windows from Debian 10

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4975]
I currently get this error building libsodium, for master (a960e896dd4c0b6d96db3d5ebbb1caa6c92a9f39) cross-compiling from Debian 10:
```
Building libsodium...
make[1]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108'
Making all in builds
make[2]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/builds'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/builds'
Making all in contrib
make[2]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/contrib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/contrib'
Making all in dist-build
make[2]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/dist-build'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/dist-build'
Making all in msvc-scripts
make[2]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/msvc-scripts'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/msvc-scripts'
Making all in src
make[2]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/src'
Making all in libsodium
make[3]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/src/libsodium'
Making all in include
make[4]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/src/libsodium/include'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/src/libsodium/include'
make[4]: Entering directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/src/libsodium'
  CC       crypto_shorthash/siphash24/libsodium_la-shorthash_siphashx24.lo
  CC       crypto_shorthash/siphash24/ref/libsodium_la-shorthash_siphashx24_ref.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-obsolete.lo
  CC       crypto_generichash/blake2b/ref/libssse3_la-blake2b-compress-ssse3.lo
  CC       crypto_pwhash/argon2/libssse3_la-argon2-fill-block-ssse3.lo
  CC       crypto_generichash/blake2b/ref/libsse41_la-blake2b-compress-sse41.lo
  CC       crypto_generichash/blake2b/ref/libavx2_la-blake2b-compress-avx2.lo
  CC       crypto_pwhash/argon2/libavx2_la-argon2-fill-block-avx2.lo
  CC       crypto_stream/salsa20/xmm6int/libavx2_la-salsa20_xmm6int-avx2.lo
  CC       crypto_pwhash/argon2/libavx512f_la-argon2-fill-block-avx512f.lo
  CC       crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo
In file included from crypto_pwhash/argon2/argon2-fill-block-ssse3.c:36:
crypto_pwhash/argon2/blamka-round-ssse3.h:11:9: warning: '_mm_roti_epi64' macro redefined [-Wmacro-redefined]
#define _mm_roti_epi64(x, c)                                         \
        ^
/home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/lib/clang/11.0.1/include/xopintrin.h:236:9: note: previous definition is here
#define _mm_roti_epi64(A, N) \
        ^
  CC       crypto_aead/xchacha20poly1305/sodium/libsodium_la-aead_xchacha20poly1305.lo
In file included from crypto_generichash/blake2b/ref/blake2b-compress-ssse3.c:19:
crypto_generichash/blake2b/ref/blake2b-compress-ssse3.h:8:9: warning: '_mm_roti_epi64' macro redefined [-Wmacro-redefined]
#define _mm_roti_epi64(x, c)                                         \
        ^
/home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/lib/clang/11.0.1/include/xopintrin.h:236:9: note: previous definition is here
#define _mm_roti_epi64(A, N) \
        ^
In file included from crypto_generichash/blake2b/ref/blake2b-compress-sse41.c:25:
crypto_generichash/blake2b/ref/blake2b-compress-sse41.h:8:9: warning: '_mm_roti_epi64' macro redefined [-Wmacro-redefined]
#define _mm_roti_epi64(x, c)                                         \
        ^
/home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/lib/clang/11.0.1/include/xopintrin.h:236:9: note: previous definition is here
#define _mm_roti_epi64(A, N) \
        ^
  CC       crypto_auth/libsodium_la-crypto_auth.lo
1 warning generated.
  CC       crypto_auth/hmacsha256/libsodium_la-auth_hmacsha256.lo
  CC       crypto_auth/hmacsha512/libsodium_la-auth_hmacsha512.lo
  CC       crypto_auth/hmacsha512256/libsodium_la-auth_hmacsha512256.lo
1 warning generated.
1 warning generated.
  CC       crypto_box/libsodium_la-crypto_box.lo
  CC       crypto_box/libsodium_la-crypto_box_easy.lo
  CC       crypto_box/libsodium_la-crypto_box_seal.lo
  CC       crypto_box/curve25519xsalsa20poly1305/libsodium_la-box_curve25519xsalsa20poly1305.lo
  CC       crypto_core/ed25519/ref10/libsodium_la-ed25519_ref10.lo
  CC       crypto_core/hchacha20/libsodium_la-core_hchacha20.lo
  CC       crypto_core/hsalsa20/ref2/libsodium_la-core_hsalsa20_ref2.lo
  CC       crypto_core/hsalsa20/libsodium_la-core_hsalsa20.lo
  CC       crypto_core/salsa/ref/libsodium_la-core_salsa_ref.lo
  CC       crypto_generichash/libsodium_la-crypto_generichash.lo
  CC       crypto_generichash/blake2b/libsodium_la-generichash_blake2.lo
  CC       crypto_generichash/blake2b/ref/libsodium_la-blake2b-compress-ref.lo
  CC       crypto_generichash/blake2b/ref/libsodium_la-blake2b-ref.lo
  CC       crypto_generichash/blake2b/ref/libsodium_la-generichash_blake2b.lo
  CC       crypto_hash/libsodium_la-crypto_hash.lo
  CC       crypto_hash/sha256/libsodium_la-hash_sha256.lo
  CC       crypto_hash/sha256/cp/libsodium_la-hash_sha256_cp.lo
  CC       crypto_hash/sha512/libsodium_la-hash_sha512.lo
  CC       crypto_hash/sha512/cp/libsodium_la-hash_sha512_cp.lo
  CC       crypto_kdf/blake2b/libsodium_la-kdf_blake2b.lo
  CC       crypto_kdf/libsodium_la-crypto_kdf.lo
  CC       crypto_kx/libsodium_la-crypto_kx.lo
  CC       crypto_onetimeauth/libsodium_la-crypto_onetimeauth.lo
  CC       crypto_onetimeauth/poly1305/libsodium_la-onetimeauth_poly1305.lo
  CC       crypto_onetimeauth/poly1305/donna/libsodium_la-poly1305_donna.lo
  CC       crypto_pwhash/argon2/libsodium_la-argon2-core.lo
  CC       crypto_pwhash/argon2/libsodium_la-argon2-encoding.lo
  CC       crypto_pwhash/argon2/libsodium_la-argon2-fill-block-ref.lo
  CC       crypto_pwhash/argon2/libsodium_la-argon2.lo
  CC       crypto_pwhash/argon2/libsodium_la-blake2b-long.lo
  CC       crypto_pwhash/argon2/libsodium_la-pwhash_argon2i.lo
  CC       crypto_pwhash/argon2/libsodium_la-pwhash_argon2id.lo
  CC       crypto_pwhash/libsodium_la-crypto_pwhash.lo
  CC       crypto_scalarmult/libsodium_la-crypto_scalarmult.lo
  CC       crypto_scalarmult/curve25519/ref10/libsodium_la-x25519_ref10.lo
  CC       crypto_scalarmult/curve25519/libsodium_la-scalarmult_curve25519.lo
  CC       crypto_secretbox/libsodium_la-crypto_secretbox.lo
  CC       crypto_secretbox/libsodium_la-crypto_secretbox_easy.lo
  CC       crypto_secretbox/xsalsa20poly1305/libsodium_la-secretbox_xsalsa20poly1305.lo
  CC       crypto_secretstream/xchacha20poly1305/libsodium_la-secretstream_xchacha20poly1305.lo
  CC       crypto_shorthash/libsodium_la-crypto_shorthash.lo
  CC       crypto_shorthash/siphash24/libsodium_la-shorthash_siphash24.lo
  CC       crypto_shorthash/siphash24/ref/libsodium_la-shorthash_siphash24_ref.lo
  CC       crypto_sign/libsodium_la-crypto_sign.lo
  CC       crypto_sign/ed25519/libsodium_la-sign_ed25519.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-keypair.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-open.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-sign.lo
  CC       crypto_stream/chacha20/libsodium_la-stream_chacha20.lo
  CC       crypto_stream/chacha20/ref/libsodium_la-chacha20_ref.lo
  CC       crypto_stream/libsodium_la-crypto_stream.lo
  CC       crypto_stream/salsa20/libsodium_la-stream_salsa20.lo
  CC       crypto_stream/xsalsa20/libsodium_la-stream_xsalsa20.lo
  CC       crypto_verify/sodium/libsodium_la-verify.lo
  CC       randombytes/libsodium_la-randombytes.lo
  CC       sodium/libsodium_la-codecs.lo
  CC       sodium/libsodium_la-core.lo
  CC       sodium/libsodium_la-runtime.lo
  CC       sodium/libsodium_la-utils.lo
  CC       sodium/libsodium_la-version.lo
  CC       crypto_stream/salsa20/ref/libsodium_la-salsa20_ref.lo
  CC       crypto_box/curve25519xchacha20poly1305/libsodium_la-box_curve25519xchacha20poly1305.lo
  CC       crypto_box/curve25519xchacha20poly1305/libsodium_la-box_seal_curve25519xchacha20poly1305.lo
  CC       crypto_core/ed25519/libsodium_la-core_ed25519.lo
  CC       crypto_core/ed25519/libsodium_la-core_ristretto255.lo
  CC       crypto_pwhash/scryptsalsa208sha256/libsodium_la-crypto_scrypt-common.lo
  CC       crypto_pwhash/scryptsalsa208sha256/libsodium_la-scrypt_platform.lo
  CC       crypto_pwhash/scryptsalsa208sha256/libsodium_la-pbkdf2-sha256.lo
  CC       crypto_pwhash/scryptsalsa208sha256/libsodium_la-pwhash_scryptsalsa208sha256.lo
  CC       crypto_pwhash/scryptsalsa208sha256/nosse/libsodium_la-pwhash_scryptsalsa208sha256_nosse.lo
  CC       crypto_scalarmult/ed25519/ref10/libsodium_la-scalarmult_ed25519_ref10.lo
  CC       crypto_scalarmult/ristretto255/ref10/libsodium_la-scalarmult_ristretto255_ref10.lo
  CC       crypto_secretbox/xchacha20poly1305/libsodium_la-secretbox_xchacha20poly1305.lo
  CC       crypto_stream/salsa2012/ref/libsodium_la-stream_salsa2012_ref.lo
  CC       crypto_stream/salsa2012/libsodium_la-stream_salsa2012.lo
  CC       crypto_stream/salsa208/ref/libsodium_la-stream_salsa208_ref.lo
  CC       crypto_stream/salsa208/libsodium_la-stream_salsa208.lo
  CC       crypto_stream/xchacha20/libsodium_la-stream_xchacha20.lo
  CC       randombytes/sysrandom/libsodium_la-randombytes_sysrandom.lo
  CC       crypto_aead/aes256gcm/aesni/libaesni_la-aead_aes256gcm_aesni.lo
  CC       crypto_onetimeauth/poly1305/sse2/libsse2_la-poly1305_sse2.lo
  CC       crypto_pwhash/scryptsalsa208sha256/sse/libsse2_la-pwhash_scryptsalsa208sha256_sse.lo
  CC       crypto_stream/salsa20/xmm6int/libsse2_la-salsa20_xmm6int-sse2.lo
  CC       crypto_stream/chacha20/dolbeau/libssse3_la-chacha20_dolbeau-ssse3.lo
  CCLD     libsse41.la
  CC       crypto_stream/chacha20/dolbeau/libavx2_la-chacha20_dolbeau-avx2.lo
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
  CCLD     libavx512f.la
  CC       randombytes/internal/librdrand_la-randombytes_internal_random.lo
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
  CCLD     libaesni.la
  CCLD     libssse3.la
  CCLD     libsse2.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
  CCLD     libavx2.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
In file included from randombytes/internal/randombytes_internal_random.c:55:
In file included from ./include/sodium/private/common.h:248:
In file included from /home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/lib/clang/11.0.1/include/intrin.h:12:
In file included from /usr/x86_64-w64-mingw32/include/intrin.h:41:
/usr/x86_64-w64-mingw32/include/psdk_inc/intrin-impl.h:1944:18: error: function cannot return function type 'int (unsigned int)'
unsigned __int64 _xgetbv(unsigned int);
                 ^
/home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/lib/clang/11.0.1/include/xsaveintrin.h:35:42: note: expanded from macro '_xgetbv'
#define _xgetbv(A) __builtin_ia32_xgetbv((long long)(A))
                                         ^
In file included from randombytes/internal/randombytes_internal_random.c:55:
In file included from ./include/sodium/private/common.h:248:
In file included from /home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/lib/clang/11.0.1/include/intrin.h:12:
In file included from /usr/x86_64-w64-mingw32/include/intrin.h:41:
/usr/x86_64-w64-mingw32/include/psdk_inc/intrin-impl.h:1947:18: error: function cannot return function type 'int (unsigned int)'
unsigned __int64 _xgetbv(unsigned int index)
                 ^
/home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/lib/clang/11.0.1/include/xsaveintrin.h:35:42: note: expanded from macro '_xgetbv'
#define _xgetbv(A) __builtin_ia32_xgetbv((long long)(A))
                                         ^
randombytes/internal/randombytes_internal_random.c:128:8: warning: unknown attribute 'thread' ignored [-Wunknown-attributes]
static TLS InternalRandom stream = {
       ^
randombytes/internal/randombytes_internal_random.c:98:26: note: expanded from macro 'TLS'
#  define TLS __declspec(thread)
                         ^
1 warning and 2 errors generated.
make[4]: *** [Makefile:2307: randombytes/internal/librdrand_la-randombytes_internal_random.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/src/libsodium'
make[3]: *** [Makefile:3111: all-recursive] Error 1
make[3]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/src/libsodium'
make[2]: *** [Makefile:400: all-recursive] Error 1
make[2]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/src'
make[1]: *** [Makefile:515: all-recursive] Error 1
make[1]: Leaving directory '/home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108'
make: *** [funcs.mk:248: /home/daira/zecc/zcash.quick/depends/work/build/x86_64-w64-mingw32/libsodium/1.0.18-3c017882108/./.stamp_built] Error 2
make: Leaving directory '/home/daira/zecc/zcash.quick/depends'
```

Related (but no fix there): https://bugs.llvm.org/show_bug.cgi?id=43642

It appears that clang is defining the [_xgetbv](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-managing-extended-processor-states-and-registers/intrinsics-for-reading-and-writing-the-content-of-extended-control-registers/xgetbv.html) intrinsic as a macro, and then the mingw headers are declaring it, so that the declaration expands to a syntax error.

This appears to be a separate issue to #4848.

**Comment by daira** [comment]
It looks as though this might be fixed in latest MinGW-w64: https://sourceforge.net/p/mingw-w64/mailman/message/36519293/

**Comment by str4d** [comment]
I do not encounter this bug when cross-compiling with Ubuntu 20.04, mingw-w64 7.0.0-2.

**Comment by daira** [comment]
The above build output is with mingw-w64 6.0.0-3, which is the most recent package on Debian 10 stable. I also tried 8.0.0-1 which is the most recent package in unstable, and got the same error. Perhaps Ubuntu's package has patches that Debian's doesn't?

In any case I think we should treat the MinGW headers as a pinned dependency rather than something that comes from the build platform.

**Comment by str4d** [comment]
@daira and I paired on this, and determined that the above issue was fixed in MinGW 7: https://github.com/mirror/mingw-w64/commit/8b2c7826b8d68e2ffc79c286b8792efe4168f666

I think the issue here is local to @daira's environment (perhaps the MinGW 6 headers were not entirely replaced by MinGW 8 during the upgrade?)

**Comment by daira** [comment]
The problem appears to be that `/usr/share/mingw-w64/include/psdk_inc/intrin-impl.h` is not "owned" by the `mingw-w32` package. According to `dpkg -S`, it's owned by `mingw-w64-common`, which was still on 6.0.0-3.

This is a bit strange because `mingw-w64-common` is an indirect dependency of `mingw-w32` (confirmed using `apt-cache depends --recurse mingw-w64 |grep 'mingw-w64-common'`), so upgrading the latter *should* have upgraded the former. Maybe it didn't because I was getting `mingw-w32` from unstable.

In any case, `sudo apt-get install --upgrade -t unstable mingw-w64-common` results in a `/usr/share/mingw-w64/include/psdk_inc/intrin-impl.h` with the patch.

*However*, building master with that upgrade gives the following error:
```
  "clang++" "-target" "x86_64-w64-mingw32" "-B/home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/bin" "-stdlib=libc++" -c -x c++ -fvisibility-inlines-hidden -pipe -isystem /home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/include/c++/v1 -O3 -std=c++17 -fvisibility=hidden     -m64 -O3 -Wall -fvisibility=hidden -Wno-inline -pthread -I/home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/include     -Wextra -Wno-long-long -Wno-unused-parameter -Wno-variadic-macros -Wunused-function -DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_USES_CHRONO -DBOOST_THREAD_WIN32 -DBOOST_USE_WINDOWS_H -DNDEBUG -DWIN32_LEAN_AND_MEAN -I"."  -o "bin.v2/libs/thread/build/clang-linux-11.0.1/release/link-static/target-os-windows/threadapi-win32/threading-multi/visibility-hidden/future.obj" "libs/thread/src/future.cpp"

In file included from libs/thread/src/future.cpp:10:
In file included from ./boost/thread/futures/future_error_code.hpp:13:
In file included from ./boost/system/error_code.hpp:15:
In file included from ./boost/cstdint.hpp:71:
In file included from /home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/include/c++/v1/stdint.h:123:
In file included from /home/daira/zecc/zcash.quick/depends/x86_64-w64-mingw32/native/lib/clang/11.0.1/include/stdint.h:52:
In file included from /usr/x86_64-w64-mingw32/include/stdint.h:28:
/usr/x86_64-w64-mingw32/include/crtdefs.h:10:10: fatal error: 'corecrt.h' file not found
#include <corecrt.h>
         ^~~~~~~~~~~
1 error generated.
```

**Comment by daira** [comment]
OK this fixed it:
```
sudo apt-get install --upgrade -t unstable mingw-w64 mingw-w64-tools mingw-w64-common mingw-w64-x86-64-dev mingw-w64-i686-dev
```

modulo the following link warnings:
```
  CXXLD    zcash-cli.exe
  CXXLD    zcashd.exe
  CXXLD    bench/bench_bitcoin.exe
  CXXLD    zcash-gtest.exe
  CXXLD    zcash-tx.exe
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_uncaught_exceptions (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_decrement_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_increment_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_current_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_rethrow_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_uncaught_exceptions (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_decrement_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_increment_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_current_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_rethrow_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_uncaught_exceptions (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_decrement_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_increment_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_current_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_rethrow_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_uncaught_exceptions (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_decrement_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_increment_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_current_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_rethrow_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: gtest/zcash_gtest-test_checktransaction.o: locally defined symbol imported: __cxa_demangle (defined in libc++abi.a(cxa_demangle.cpp.obj)) [LNK4217]
lld-link: warning: gtest/zcash_gtest-test_zip32.o: locally defined symbol imported: __cxa_demangle (defined in libc++abi.a(cxa_demangle.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_uncaught_exceptions (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_decrement_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_increment_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_current_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_rethrow_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
  CXXLD    test/test_bitcoin.exe
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_uncaught_exceptions (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_decrement_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_increment_exception_refcount (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_current_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libc++.a(exception.cpp.obj): locally defined symbol imported: __cxa_rethrow_primary_exception (defined in libc++abi.a(cxa_exception.cpp.obj)) [LNK4217]
lld-link: warning: libboost_unit_test_framework.a(execution_monitor.obj): locally defined symbol imported: __cxa_demangle (defined in libc++abi.a(cxa_demangle.cpp.obj)) [LNK4217]
```

**Comment by str4d** [comment]
Cool, so this suggests that cross-compilation should indeed work on Ubuntu 20.04 or Debian 10 under MinGW 7 and 8.

**Comment by mdr0id** [comment]
I'm still unable to get a build per the above command with some minor edits to `/etc/apt/sources.list`. Also what is the suggested alternative for Ubuntu since `unstable` is not valid thing in Ubuntu apt land?

**Comment by str4d** [comment]
@mdr0id I haven't made any source changes to Ubuntu 20.04; I'm using the `mingw-w64 7.0.0-2` available by default (https://packages.ubuntu.com/focal/mingw-w64).

**Comment by bigbrain** [comment]
I also had this error when compiling for Windows from stable version Debian 10.8.0. The problem was solved by updating mingw from unstable source to version 8 as suggested by @daira 

First I had to write the unstable source in the `/etc/apt/sources.list`
```
# Change to local mirror
deb http://deb.debian.org/debian/ unstable main contrib
```
Then:
```
sudo apt-get update
sudo apt-get install --upgrade -t unstable mingw-w64 mingw-w64-tools mingw-w64-common mingw-w64-x86-64-dev mingw-w64-i686-dev
```
But I think it's not a good idea for a stable version of Debian. Maybe there is some way to add mingw in dependencies?

Then on compilation, I went back to the error with `_ISspace`.
But I compiled zcash-4.3.0-rc1 successfully when I removed all multilib packages.
I had these packages: `g++-multilib`, `g++-8-multilib`, `gcc-multilib`, `gcc-8-multilib`.
